public enum TokenType {
    COMMA, Dividing, ELSE, ELSEIF, EQUAL, End, FALSE, FOR, FUNCTION, GREATER, GREATER_EQUAL, IDENTIFIER, IF, SWICH,
    LBRACE, LESS, LESS_EQUAL, LPAREN, NOT, NOT_EQUAL, Number, PRINT, RBRACE, RETURNS, INCREMENT, ADD_ASSIGN, RPAREN, Remainder, SEMICOLON, STRING, TRUE, Var, WHILE, add, assignment, multiply, DECREMENT, SUB_ASSIGN, MUL_ASSIGN, DIV_ASSIGN, OR, AND, remove,exegesis
}
enum ValueType {
    NUMBER, STRING, BOOLEAN, FUNCTION, NULL
}
